# Generated by Django 5.2.1 on 2025-05-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'inactivo')], default='activo', max_length=10),
        ),
    ]
