# Generated by Django 5.2.1 on 2025-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_especialidad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=10),
        ),
    ]
