# Generated by Django 5.2.1 on 2025-05-16 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_especialidad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('vacuna', 'Vacuna'), ('higiene', 'Higiene y cuidado'), ('alimento', 'Alimento y suplemento'), ('venta', 'Producto para venta directa')], max_length=20)),
                ('subtipo', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=10)),
            ],
        ),
    ]
