# Generated by Django 5.2.1 on 2025-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consultorio_responsable_tipodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='disponible',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
    ]
