# Generated by Django 5.2.1 on 2025-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_consultorio_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
