# Generated by Django 5.2.1 on 2025-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_especialidad_options_alter_especialidad_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='disponible',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10),
        ),
    ]
